language: node_js
node_js: stable
script: npm run lint
deploy:
  provider: npm
  email: i@mudkip.me
  api_key:
    secure: oQNt+4KJvkTc7bRtPu0OGTWeVyfnXl6wC0/p9CN7xwP7erMlO2RbwaMWinLPK4+dCOuvaICzI4GC5jTUTEquAOw/F7GWVt8VAyGdEvgdwfco3ygmETWOUFiOS2Xl86quQf3Zr7/aXYAFxKlf0jSQFH3n0flR2oyKqes44bNetfg7UT5IE9dSDVjl8bGLjWwinLBaDelRWeH7Pmr9IhspWGtnOds44QgmoWN1X347nVygwmW6Lc+Q+BzgnmrOnXW7yxAXp6A/L8+S9oL4FHS4PBK9CvoWeC55u30FoT0muGx1KF6iYYWOBOHNcgqFhfBvmqS3lPKSeJHVb4jBpubJw0ghHUNxpIjn0xtNryXN0JfLAkd0sopAtomdVlBlhddnnf3H59NnkgmMkGKJ+PRWnMZ0ut2lkEAwmtpFDElGADEKGVpa76mi83hT1LxBxJwRxi1IklPY4QbelhxnXagLuNosBV69I9vGt5KvkwzCwuJ0U+cxy3W5mhMsE15X12fQJpMhCa9m+uayUI3sOBy9wtx8W2c39SzyInPVKJh6oaRaOkZ179DVWEsg9OCFgAzsBCYA5Ael9+EmmMztbbiouigyKgWgGHrIdyet3RetfyRrr665oJg/Xts2WHlQ8l+SU3U4qcpBaevUecV9Zd0IOzxgeZewrZ4kUnCxJbDHXpI=
  on:
    tags: true
